version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        STAGE: ${STAGE}             # Build stage (e.g., development)
    
    # Set the working directory for the commands in the container
    working_dir: "/app"
    
    # Mount the current directory into the container, using cached mode
    volumes:
      - ./:/app:cached
    
    # Load environment variables from the .env file
    env_file:
      - .env
    
    command: bash -c "while true; do echo hello; sleep 2; done"
